name: CI

on:
  # # Trigger on push/pull from master
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Also able to run manually
  workflow_dispatch:

jobs:

  deploy-infra:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region:  ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: MySessionName

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.10.1"

      - name: terraform init
        id: init
        run: terraform init

      # - name: terraform validate
      #   id: validate
      #   run: terraform validate

      # - name: terraform plan
      #   id: plan
      #   run: terraform plan -no-color -out plan.bin | tee plan.out

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          aws sts get-caller-identity

      - name: Unset the credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          unset-current-credentials: true


